<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOuznez6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOuznez6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOuznez6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOuznez6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOuznez6\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ouznez6',
    'container.build_id' => '47ce58e3',
    'container.build_time' => 1525758060,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOuznez6');
